# From ChatGPT
name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get install -y g++

    - name: Build the project
      run: make

    - name: Run tests
      run: ./bin/main_test

    - name: Clean up
      run: make clean
