name: CMake Build and Test

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Specify the platforms

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake (for Ubuntu and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          sudo apt-get install -y cmake || brew install cmake  # For macOS

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: |
          cd build
          cmake .. -G "Unix Makefiles" # Adjust flags if necessary for specific platforms

      - name: Build the project
        run: |
          cd build
          cmake --build . --config Release

      - name: Run main_test.exe
        run: |
          cd build
          if [ ${{ runner.os }} == 'Windows' ]; then
            .\bin\main_test.exe
          else
            ./bin/main_test
          fi
