# From ChatGPT
name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      PATH: C:\ProgramData\chocolater\bin;${{ github.env.PATH }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: choco install mingw

    - name: Verify g++ installation
      run: g++ --version

    - name: Build the project
      run: mingw32-make

    - name: Run tests
      run: ./bin/main_test

    - name: Clean up
      run: make clean
